CREATE TABLE CARROS (
  CARRO_ID NUMBER(5, 0) NOT NULL,
  FECHA_DE_CREACION DATE,
  COLOR VARCHAR2(400 BYTE),
  FABRICANTE_ID NUMBER(5, 0),
  CARRO_DETALLES VARCHAR2(400 BYTE),
  path_to_iamge BFILE,
  CONSTRAINT CARROS_PK PRIMARY KEY ( CARRO_ID ) USING INDEX ( CREATE UNIQUE INDEX CARROS_PK ON CARROS (CARRO_ID ASC) LOGGING TABLESPACE USERS PCTFREE 10 INITRANS 2 STORAGE ( BUFFER_POOL DEFAULT ) NOPARALLEL ) ENABLE
) LOGGING TABLESPACE USERS PCTFREE 10 INITRANS 1 STORAGE (
  BUFFER_POOL DEFAULT
) NOCOMPRESS NO INMEMORY NOPARALLEL;

ALTER TABLE CARROS ADD CONSTRAINT FABRICANTE_ID_FK FOREIGN KEY ( FABRICANTE_ID ) REFERENCES FABRICANTES ( FABRICANTE_ID ) ENABLE;

ALTER TABLE CARROS ADD CONSTRAINT MODELO_ID_FK FOREIGN KEY ( MARCA_CARRO_ID ) REFERENCES MODELO_DE_CARRO ( MODELO_ID ) ENABLE;

CREATE TABLE dueno_carro (
  dueno_id NUMBER(5, 0) NOT NULL,
  NOMBRE VARCHAR2(400 BYTE),
  dueno_direccion VARCHAR2(3400BYTE),
  CARRO_ID NUMBER,
  CONSTRAINT dueno_carro_PK PRIMARY KEY ( dueno_id ) USING INDEX ( CREATE UNIQUE INDEX dueno_carro_PK ON dueno_carro (dueno_id ASC) LOGGING TABLESPACE USERS PCTFREE 10 INITRANS 2 STORAGE ( BUFFER_POOL DEFAULT ) NOPARALLEL ) ENABLE
) LOGGING TABLESPACE USERS PCTFREE 10 INITRANS 1 STORAGE (
  BUFFER_POOL DEFAULT
) NOCOMPRESS NO INMEMORY NOPARALLEL;

ALTER TABLE dueno_carro ADD CONSTRAINT CARRO_ID_FK FOREIGN KEY ( CARRO_ID ) REFERENCES CARROS ( CARRO_ID ) ENABLE;

CREATE TABLE FABRICANTES (
  FABRICANTE_ID NUMBER(5, 0) NOT NULL,
  FABRICANTE_NOMBRE VARCHAR2(400 BYTE),
  FABRICANTE_UBICACION VARCHAR2(400 BYTE),
  FABRICANTE_DETALLES VARCHAR2(400 BYTE),
  CONSTRAINT FABRICANTES_PK PRIMARY KEY ( FABRICANTE_ID ) USING INDEX ( CREATE UNIQUE INDEX FABRICANTES_PK ON FABRICANTES (FABRICANTE_ID ASC) LOGGING TABLESPACE USERS PCTFREE 10 INITRANS 2 STORAGE ( BUFFER_POOL DEFAULT ) NOPARALLEL ) ENABLE
) LOGGING TABLESPACE USERS PCTFREE 10 INITRANS 1 STORAGE (
  BUFFER_POOL DEFAULT
) NOCOMPRESS NO INMEMORY NOPARALLEL;

CREATE TABLE HISTORIAL_DE_SERVICIOS (
  SERVICIO_ID NUMBER(5, 0) NOT NULL,
  FECHA_ULTIMO_SERVICIO DATE NOT NULL,
  DETALLES_ULT_SERVICIO VARCHAR2(400 BYTE),
  CARRO_ID NUMBER,
  CONSTRAINT HISTORIAL_DE_SERVICIOS_PK PRIMARY KEY ( SERVICIO_ID ) USING INDEX ( CREATE UNIQUE INDEX HISTORIAL_DE_SERVICIOS_PK ON HISTORIAL_DE_SERVICIOS (SERVICIO_ID ASC) LOGGING TABLESPACE USERS PCTFREE 10 INITRANS 2 STORAGE ( BUFFER_POOL DEFAULT ) NOPARALLEL ) ENABLE
) LOGGING TABLESPACE USERS PCTFREE 10 INITRANS 1 STORAGE (
  BUFFER_POOL DEFAULT
) NOCOMPRESS NO INMEMORY NOPARALLEL;

ALTER TABLE HISTORIAL_DE_SERVICIOS ADD CONSTRAINT HISTORIAL_DE_SERVICIOS_FK1 FOREIGN KEY ( CARRO_ID ) REFERENCES CARROS ( CARRO_ID ) ENABLE;

CREATE TABLE MANTENIMIENTO_CARRO (
  MANTENIMIENTO_ID NUMBER NOT NULL,
  FECHA_INICIO DATE,
  FECHA_FINAL DATE,
  PROBLEMA_CARRO VARCHAR2(600 BYTE),
  CARRO_ID NUMBER,
  PROVEEDOR_ID NUMBER,
  CONSTRAINT MANTENIMIENTO_CARRO_PK PRIMARY KEY ( MANTENIMIENTO_ID ) USING INDEX ( CREATE UNIQUE INDEX MANTENIMIENTO_CARRO_PK ON MANTENIMIENTO_CARRO (MANTENIMIENTO_ID ASC) LOGGING TABLESPACE USERS PCTFREE 10 INITRANS 2 STORAGE ( BUFFER_POOL DEFAULT ) NOPARALLEL ) ENABLE
) LOGGING TABLESPACE USERS PCTFREE 10 INITRANS 1 STORAGE (
  BUFFER_POOL DEFAULT
) NOCOMPRESS NO INMEMORY NOPARALLEL;

ALTER TABLE MANTENIMIENTO_CARRO ADD CONSTRAINT MANTENIMIENTO_CARRO_FK1 FOREIGN KEY ( CARRO_ID ) REFERENCES CARROS ( CARRO_ID ) ENABLE;

ALTER TABLE MANTENIMIENTO_CARRO ADD CONSTRAINT MANTENIMIENTO_CARRO_FK2 FOREIGN KEY ( PROVEEDOR_ID ) REFERENCES PROVEEDORES ( PROVEEDOR_ID ) ENABLE;

CREATE TABLE MODELO_DE_CARRO (
  MODELO_ID NUMBER(5, 0) NOT NULL,
  MODELO_NOMBRE VARCHAR2(400 BYTE),
  MODELO_DESCRIPCION VARCHAR2(500 BYTE),
  CONSTRAINT MODELO_DE_VEHICULO_PK PRIMARY KEY ( MODELO_ID ) USING INDEX ( CREATE UNIQUE INDEX MODELO_DE_VEHICULO_PK ON MODELO_DE_CARRO (MODELO_ID ASC) LOGGING TABLESPACE USERS PCTFREE 10 INITRANS 2 STORAGE ( BUFFER_POOL DEFAULT ) NOPARALLEL ) ENABLE
) LOGGING TABLESPACE USERS PCTFREE 10 INITRANS 1 STORAGE (
  BUFFER_POOL DEFAULT
) NOCOMPRESS NO INMEMORY NOPARALLEL;

CREATE TABLE PROVEEDORES (
  PROVEEDOR_ID NUMBER(5, 0) NOT NULL,
  PROVEEDOR_NOMBRE VARCHAR2(400 BYTE),
  PROVEEDOR_DIRECCION VARCHAR2(400 BYTE),
  PROVEEDOR_DETALLES VARCHAR2(500 BYTE),
  CONSTRAINT PROVEEDORES_PK PRIMARY KEY ( PROVEEDOR_ID ) USING INDEX ( CREATE UNIQUE INDEX PROVEEDORES_PK ON PROVEEDORES (PROVEEDOR_ID ASC) LOGGING TABLESPACE USERS PCTFREE 10 INITRANS 2 STORAGE ( BUFFER_POOL DEFAULT ) NOPARALLEL ) ENABLE
) LOGGING TABLESPACE USERS PCTFREE 10 INITRANS 1 STORAGE (
  BUFFER_POOL DEFAULT
) NOCOMPRESS NO INMEMORY NOPARALLEL;

ALTER TABLE CARROS RENAME COLUMN VELOCIDAD_MAX TO PATH_TO_IMAGE;

ALTER TABLE CARROS RENAME COLUMN MARCA_CARRO_ID TO MODELO_CARRO_ID;

alter table DUENO_CARRO drop column CARRO_ID cascade constraints;

ALTER TABLE PROVEEDORES DROP CONSTRAINT PROVEEDORES_PK;
drop TABLE proveedores;
